#!/usr/bin/env python3
"""MyAgents Unified CLI - Agent interaction and Studio management.

This CLI has been refactored to use workflow classes from Phase 1
of the CLI Workflow Refactoring plan.
"""

import sys
import os
import argparse
import subprocess
from pathlib import Path

# Lazy imports to speed up CLI startup
# These will be imported on-demand by specific commands

# Global variables set by run_cli()
project_dir = None
config_path = None


def get_version():
    """Get the myagents package version.

    Delegates to HelpWorkflow.show_version().

    Returns:
        str: Version string in format "myagents X.Y.Z"
    """
    from myagents.backend.services.agents.workflows.help_workflow import HelpWorkflow
    workflow = HelpWorkflow()
    return workflow.show_version()


def run_cli(project_root: Path, config_file: Path | None, is_global: bool = False):
    """Entry point called by frontend.cli.entry module.

    All commands now work from any directory using home directory configuration.

    Args:
        project_root: Project root directory (uses home directory or CLI installation as fallback)
        config_file: Config file path (may be None if no config found)
        is_global: Ignored, kept for backward compatibility
    """
    global project_dir, config_path
    project_dir = project_root
    config_path = config_file
    main()


def _write_env_file_for_chat(project_root: Path) -> None:
    """Write .env file for LangGraph chat session compatibility.

    Auto-generates .env file from gcptoolkit secrets. This ensures compatibility
    with LangGraph runtime which may check for .env file.

    Args:
        project_root: Path to project root directory (unused, kept for compatibility)

    Note:
        - File is written to ~/.config/myagents/.env
        - GEMINI_API_KEY is mapped to GOOGLE_API_KEY (LangGraph expects this name)
        - Errors are logged but don't fail the operation (subprocess env still works)
    """
    from myagents.backend.services.agents.domains.secrets import get_secret

    config_dir = Path.home() / ".config" / "myagents"
    config_dir.mkdir(parents=True, exist_ok=True)
    env_file_path = config_dir / ".env"

    try:
        # Get secrets from gcptoolkit
        gemini_key = get_secret("GEMINI_API_KEY")
        langsmith_key = get_secret("LANGSMITH_API_KEY")

        # Build .env file contents
        lines = [
            "# Auto-generated by MyAgents - DO NOT EDIT",
            "# This file is automatically generated from gcptoolkit secrets",
            "# Changes will be overwritten on next chat session",
            "",
        ]

        # Track which keys were written
        keys_written = []

        # Write required keys for LangGraph
        # Note: Use GOOGLE_API_KEY (not GEMINI_API_KEY) as LangGraph expects this name
        if gemini_key:
            lines.append(f"GOOGLE_API_KEY={gemini_key}")
            keys_written.append("GOOGLE_API_KEY")
        if langsmith_key:
            lines.append(f"LANGSMITH_API_KEY={langsmith_key}")
            keys_written.append("LANGSMITH_API_KEY")

        # Add LangSmith tracing configuration
        lines.append("LANGSMITH_TRACING=true")
        lines.append("LANGSMITH_PROJECT=myagents-cli-chat")

        # Write to file
        env_file_path.write_text("\n".join(lines) + "\n")

        # Show success message with keys written
        print("✓ .env file generated successfully")
        if keys_written:
            print(f"  Keys configured: {', '.join(keys_written)}")

    except Exception as e:
        # Log warning but don't fail - subprocess environment still works via gcptoolkit
        print(f"⚠ Warning: Failed to write .env file: {e}")
        print("  Chat will still work via gcptoolkit secrets in subprocess environment")


def cmd_agent_chat(args):
    """Run interactive agent chat.

    Works from any directory using home directory configuration.

    Args:
        args: Parsed command-line arguments
            - agent: Agent type to use (any registered agent type)

    Behavior:
        - Checks for gcptoolkit config (REQUIRED - fails if missing)
        - Loads API key from GCP Secret Manager
        - Auto-generates .env file for LangGraph compatibility
        - Checks Studio status and displays connection info
        - Starts interactive chat loop
        - Supports 'quit', 'exit', 'q' to exit
    """
    # Check for gcptoolkit config BEFORE any other operations
    from myagents.backend.services.agents.domains.config_checker import ensure_config_or_exit
    ensure_config_or_exit()

    # Lazy imports
    import os
    from myagents.backend.services.agents.workflows.agent_registry import (
        get_agent_runner,
        get_agent_description,
    )
    from myagents.backend.services.agents.domains.secrets import get_secret
    from myagents.backend.services.agents.workflows.studio_workflow import StudioWorkflow

    # Determine which agent to use
    agent_type = args.agent or "builder"

    # Get the agent runner dynamically from registry
    try:
        run_agent = get_agent_runner(agent_type)
        agent_desc = get_agent_description(agent_type)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Set up API key
    api_key = get_secret("GEMINI_API_KEY")
    os.environ["GOOGLE_API_KEY"] = api_key

    # Auto-generate .env file for LangGraph compatibility
    _write_env_file_for_chat(project_dir)

    # Get Studio status using StudioWorkflow
    try:
        workflow = StudioWorkflow(home_config_dir=None, config_path=config_path)
        studio_status = workflow.get_studio_status()
    except RuntimeError:
        # If secrets are not available, continue without studio status
        studio_status = {"running": False}

    print("=" * 60)
    print(f"MyAgents CLI - {agent_type} Agent")
    print(f"  {agent_desc}")
    print("=" * 60)

    if studio_status["running"]:
        print(f"[Studio] Running on port {studio_status['port']}")
        print(f"[Studio] WebUI: {studio_status['url']}")
    else:
        print("[Studio] Not running (start with: myagents studio start)")

    print("=" * 60)
    print("Type your messages below. Type 'quit' or 'exit' to end.")
    print("=" * 60)
    print()

    # Persistent state across turns
    state = None

    while True:
        try:
            user_input = input("\nYou: ").strip()

            if user_input.lower() in ['quit', 'exit', 'q']:
                print("\nGoodbye!")
                break

            if not user_input:
                continue

            print("\nAgent: ", end="", flush=True)
            try:
                response, state = run_agent(user_input, state)
                print(response)
            except Exception as e:
                print(f"\n[ERROR] Failed to get response: {e}")

        except KeyboardInterrupt:
            print("\n\nInterrupted. Goodbye!")
            break
        except EOFError:
            print("\n\nGoodbye!")
            break


def cmd_agents_list(args):
    """List all available agents in the registry.

    Shows agent names and descriptions.
    """
    from myagents.backend.services.agents.workflows.agent_registry import (
        list_agents,
        get_agent_description,
    )

    agents = list_agents()

    print("=" * 60)
    print("Available Agents")
    print("=" * 60)

    # Group agents by category
    categories = {
        "Chat Agents": ["builder", "coding"],
        "Cleaner Agents": ["cleaner-identify", "cleaner-execute"],
        "Test Agents": ["test-runner", "test-audit", "test-user-sim"],
        "Explore Agents": ["explore-architecture", "explore-feature",
                          "explore-dependency", "explore-test", "explore-synthesis"],
    }

    for category, category_agents in categories.items():
        available_in_category = [a for a in category_agents if a in agents]
        if available_in_category:
            print(f"\n{category}:")
            for agent in available_in_category:
                desc = get_agent_description(agent)
                print(f"  {agent:22} - {desc}")

    # Show any uncategorized agents
    all_categorized = set()
    for category_agents in categories.values():
        all_categorized.update(category_agents)

    uncategorized = [a for a in agents if a not in all_categorized]
    if uncategorized:
        print("\nOther Agents:")
        for agent in uncategorized:
            desc = get_agent_description(agent)
            print(f"  {agent:22} - {desc}")

    print()
    print("=" * 60)
    print("Usage: myagents chat --agent <AGENT>")
    print("       myagents clean --identify | --execute")
    print("       myagents test --run | --audit | --simulate")
    print("       myagents explore --arch | --feature | --dep | --test | --synth")
    print("=" * 60)


def cmd_clean(args):
    """Run cleaner agent.

    Two-phase cleanup process:
    - identify: Scan for cleanup targets (no changes made)
    - execute: Process approved targets

    Requires a live plan path for context.
    """
    from myagents.backend.services.agents.domains.config_checker import ensure_config_or_exit
    ensure_config_or_exit()

    import os
    from myagents.backend.services.agents.workflows.agent_registry import get_agent_runner
    from myagents.backend.services.agents.domains.secrets import get_secret

    # Determine which mode to use
    if args.identify:
        agent_type = "cleaner-identify"
        mode = "Identification"
    elif args.execute:
        agent_type = "cleaner-execute"
        mode = "Execution"
    else:
        print("Error: Must specify --identify or --execute", file=sys.stderr)
        print("  myagents clean --identify <plan_path>  - Scan for cleanup targets")
        print("  myagents clean --execute <plan_path>   - Process approved targets")
        sys.exit(1)

    # Set up API key
    api_key = get_secret("GEMINI_API_KEY")
    os.environ["GOOGLE_API_KEY"] = api_key

    print("=" * 60)
    print(f"MyAgents Cleaner - {mode} Mode")
    print("=" * 60)

    try:
        run_agent = get_agent_runner(agent_type)
        # Pass the plan path as the user input
        plan_path = args.plan_path
        response, _ = run_agent(f"Process plan: {plan_path}", None)
        print(response)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error running cleaner: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_test(args):
    """Run test agent.

    Test execution modes:
    - run: Execute tests and report results
    - audit: Review test quality and skip patterns
    - simulate: Test from user/documentation perspective
    """
    from myagents.backend.services.agents.domains.config_checker import ensure_config_or_exit
    ensure_config_or_exit()

    import os
    from myagents.backend.services.agents.workflows.agent_registry import get_agent_runner
    from myagents.backend.services.agents.domains.secrets import get_secret

    # Determine which mode to use
    if args.run:
        agent_type = "test-runner"
        mode = "Runner"
    elif args.audit:
        agent_type = "test-audit"
        mode = "Audit"
    elif args.simulate:
        agent_type = "test-user-sim"
        mode = "User Simulation"
    else:
        print("Error: Must specify --run, --audit, or --simulate", file=sys.stderr)
        print("  myagents test --run        - Execute tests and report results")
        print("  myagents test --audit      - Review test quality and skip patterns")
        print("  myagents test --simulate   - Test from user/documentation perspective")
        sys.exit(1)

    # Set up API key
    api_key = get_secret("GEMINI_API_KEY")
    os.environ["GOOGLE_API_KEY"] = api_key

    print("=" * 60)
    print(f"MyAgents Test - {mode} Mode")
    print("=" * 60)

    try:
        run_agent = get_agent_runner(agent_type)
        # Use provided target or default message
        target = getattr(args, 'target', None) or "Run tests"
        response, _ = run_agent(target, None)
        print(response)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error running test agent: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_explore(args):
    """Run explore agent.

    Codebase exploration modes:
    - arch: Analyze project architecture
    - feature: Analyze feature implementations
    - dep: Map project dependencies
    - test: Analyze testing patterns
    - synth: Combine all exploration findings
    """
    from myagents.backend.services.agents.domains.config_checker import ensure_config_or_exit
    ensure_config_or_exit()

    import os
    from myagents.backend.services.agents.workflows.agent_registry import get_agent_runner
    from myagents.backend.services.agents.domains.secrets import get_secret

    # Determine which mode to use
    if args.arch:
        agent_type = "explore-architecture"
        mode = "Architecture"
    elif args.feature:
        agent_type = "explore-feature"
        mode = "Feature"
    elif args.dep:
        agent_type = "explore-dependency"
        mode = "Dependency"
    elif args.test:
        agent_type = "explore-test"
        mode = "Test"
    elif args.synth:
        agent_type = "explore-synthesis"
        mode = "Synthesis"
    else:
        print("Error: Must specify an exploration mode", file=sys.stderr)
        print("  myagents explore --arch     - Analyze project architecture")
        print("  myagents explore --feature  - Analyze feature implementations")
        print("  myagents explore --dep      - Map project dependencies")
        print("  myagents explore --test     - Analyze testing patterns")
        print("  myagents explore --synth    - Combine all exploration findings")
        sys.exit(1)

    # Set up API key
    api_key = get_secret("GEMINI_API_KEY")
    os.environ["GOOGLE_API_KEY"] = api_key

    print("=" * 60)
    print(f"MyAgents Explorer - {mode} Mode")
    print("=" * 60)

    try:
        run_agent = get_agent_runner(agent_type)
        # Use provided target or default message
        target = getattr(args, 'target', None) or "Explore codebase"
        response, _ = run_agent(target, None)
        print(response)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error running explore agent: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_studio_start(args):
    """Start LangGraph Studio.

    Works from any directory using home directory configuration.
    Uses StudioWorkflow for all operations.

    Port resolution priority:
        1. --port flag (highest priority)
        2. studio.port preference
        3. config.yml server.port (lowest priority)

    Args:
        args: Parsed command-line arguments
            - port: Port for Studio server (default: 2024)
            - foreground: Run in foreground vs background (default: False)

    Behavior:
        - Starts LangGraph Studio process
        - Displays success message with URL or error details
        - Shows recent error logs if startup fails
        - Exits with code 0 on success, 1 on failure
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.studio_workflow import StudioWorkflow
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    try:
        # Determine port: CLI flag > preference > config default (None)
        port = None

        if args.port is not None:
            # User explicitly provided --port flag (default is None)
            port = args.port
        else:
            # Check preferences for studio.port
            pref_workflow = PreferencesWorkflow()
            success, _, pref_value = pref_workflow.get_preference(key="studio.port")
            if success and pref_value is not None:
                try:
                    port = int(pref_value)
                except (ValueError, TypeError):
                    pass  # Invalid preference, use config default

        workflow = StudioWorkflow(home_config_dir=None, config_path=config_path)
        success, message = workflow.start_studio(background=not args.foreground, port=port)

        if success:
            print(message)
        else:
            # Display failure message
            print(message)

            # Try to retrieve and display recent errors from stderr log
            recent_errors = workflow.get_recent_errors(num_lines=20)

            if recent_errors:
                print("\nRecent errors from Studio logs:")
                print(recent_errors)

        sys.exit(0 if success else 1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_studio_stop(args):
    """Stop LangGraph Studio.

    Works from any directory. Uses StudioWorkflow for all operations.
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.studio_workflow import StudioWorkflow

    try:
        workflow = StudioWorkflow(home_config_dir=None, config_path=config_path)
        success, message = workflow.stop_studio(force=args.force)
        print(message)
        sys.exit(0 if success else 1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_studio_restart(args):
    """Restart LangGraph Studio.

    Works from any directory. Uses StudioWorkflow for all operations.
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.studio_workflow import StudioWorkflow

    try:
        workflow = StudioWorkflow(home_config_dir=None, config_path=config_path)
        success, message = workflow.restart_studio()
        print(message)
        sys.exit(0 if success else 1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_studio_status(args):
    """Show LangGraph Studio status.

    Works from any directory. Uses StudioWorkflow for all operations.
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.studio_workflow import StudioWorkflow

    try:
        workflow = StudioWorkflow(home_config_dir=None, config_path=config_path)
        status = workflow.get_studio_status()

        print("=" * 60)
        print("LangGraph Studio Status")
        print("=" * 60)

        if status["running"]:
            print("Status: RUNNING")
            if "pid" in status:
                print(f"PID: {status['pid']}")
            print(f"Port: {status['port']}")
            print(f"Host: {status['host']}")
            print(f"\nWebUI: {status['url']}")
            print(f"API: {status['api_url']}")
        else:
            print("Status: STOPPED")
            print("\nTo start Studio, run:")
            print("  myagents studio start")

        print("=" * 60)
        sys.exit(0 if status["running"] else 1)
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_relay_start(args):
    """Start Relay Service.

    Works from any directory using home directory configuration.
    Uses RelayServiceWorkflow for all operations.

    Args:
        args: Parsed command-line arguments
            - port: Port for relay server (default: 8080)
            - host: Host for relay server (default: 0.0.0.0)
            - foreground: Run in foreground vs background (default: False)

    Behavior:
        - Starts relay server process
        - Displays success message with endpoints or error details
        - Shows recent error logs if startup fails
        - Exits with code 0 on success, 1 on failure
    """
    # Lazy imports
    from agent_remote.services.relay.workflows.relay_service_workflow import RelayServiceWorkflow

    try:
        workflow = RelayServiceWorkflow(home_config_dir=None)
        success, message = workflow.start_relay(
            host=args.host,
            port=args.port,
            background=not args.foreground
        )

        if success:
            print(message)
        else:
            # Display failure message
            print(message)

            # Try to retrieve and display recent errors from stderr log
            recent_errors = workflow.get_recent_errors(num_lines=20)

            if recent_errors:
                print("\nRecent errors from relay logs:")
                print(recent_errors)

        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_relay_stop(args):
    """Stop Relay Service.

    Works from any directory. Uses RelayServiceWorkflow for all operations.
    """
    # Lazy imports
    from agent_remote.services.relay.workflows.relay_service_workflow import RelayServiceWorkflow

    try:
        workflow = RelayServiceWorkflow(home_config_dir=None)
        success, message = workflow.stop_relay(force=args.force)
        print(message)
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_relay_status(args):
    """Show Relay Service status.

    Works from any directory. Uses RelayServiceWorkflow for all operations.
    """
    # Lazy imports
    from agent_remote.services.relay.workflows.relay_service_workflow import RelayServiceWorkflow

    try:
        workflow = RelayServiceWorkflow(home_config_dir=None)
        status = workflow.get_status()

        print("=" * 60)
        print("Relay Service Status")
        print("=" * 60)

        if status["running"]:
            print("Status: RUNNING")
            if "pid" in status:
                print(f"PID: {status['pid']}")
            print(f"Host: {status['host']}")
            print(f"Port: {status['port']}")
            print(f"\nWebSocket URL: {status['ws_url']}")
            print(f"Desktop endpoint: {status['desktop_endpoint']}")
            print(f"Client endpoint: {status['client_endpoint']}")
            print(f"\nActive sessions: {status['active_sessions']}")
            print(f"Health: {'HEALTHY' if status.get('healthy') else 'UNKNOWN'}")
        else:
            print("Status: STOPPED")
            print("\nTo start relay server, run:")
            print("  myagents relay start")

        print("=" * 60)
        sys.exit(0 if status["running"] else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_remote_start(args):
    """Start Remote Terminal service.

    Works from any directory using home directory configuration.
    Uses RemoteWorkflow for all operations.

    Args:
        args: Parsed command-line arguments
            - port: Port for terminal service (default: 8080)
            - relay_url: WebSocket relay URL (optional)
            - foreground: Run in foreground vs background (default: False)

    Behavior:
        - Starts Remote Terminal service process
        - Displays success message with connection info or error details
        - Shows recent error logs if startup fails
        - Exits with code 0 on success, 1 on failure

    Note:
        EXPERIMENTAL: Terminal PTY functionality is not yet implemented.
        The service starts but provides only health check endpoints.
    """
    # Display experimental warning
    print("=" * 60)
    print("EXPERIMENTAL: Remote Terminal Service")
    print("=" * 60)
    print("Note: Terminal PTY functionality is not yet implemented.")
    print("The service starts but provides only health check endpoints.")
    print("Full PTY sessions will be available in a future release.")
    print("=" * 60)
    print()

    # Lazy imports
    from agent_remote.services.terminal.workflows.remote_workflow import RemoteWorkflow

    try:
        workflow = RemoteWorkflow(home_config_dir=None)
        success, message = workflow.start_service(
            port=args.port,
            relay_url=getattr(args, 'relay_url', None),
            background=not args.foreground
        )

        if success:
            print(message)
        else:
            # Display failure message
            print(message)

            # Try to retrieve and display recent errors from stderr log
            recent_errors = workflow.get_recent_errors(num_lines=20)

            if recent_errors:
                print("\nRecent errors from Remote service logs:")
                print(recent_errors)

        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_remote_stop(args):
    """Stop Remote Terminal service.

    Works from any directory. Uses RemoteWorkflow for all operations.
    """
    # Lazy imports
    from agent_remote.services.terminal.workflows.remote_workflow import RemoteWorkflow

    try:
        workflow = RemoteWorkflow(home_config_dir=None)
        success, message = workflow.stop_service(force=args.force)
        print(message)
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_remote_status(args):
    """Show Remote Terminal service status.

    Works from any directory. Uses RemoteWorkflow for all operations.
    """
    # Lazy imports
    from agent_remote.services.terminal.workflows.remote_workflow import RemoteWorkflow

    try:
        workflow = RemoteWorkflow(home_config_dir=None)
        status = workflow.get_status()

        print("=" * 60)
        print("Remote Terminal Service Status")
        print("=" * 60)

        if status["running"]:
            print("Status: RUNNING")
            if "pid" in status:
                print(f"PID: {status['pid']}")
            print(f"Port: {status['port']}")
            if "uptime" in status:
                print(f"Uptime: {status['uptime']}")
            print(f"\nWebSocket URL: {status['websocket_url']}")
            print("\nConnection Info:")
            print("  Desktop clients can connect to create terminal sessions")
        else:
            print("Status: STOPPED")
            print("\nTo start Remote Terminal service, run:")
            print("  myagents remote start")

        print("=" * 60)
        sys.exit(0 if status["running"] else 1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_preferences_get(args):
    """Get a preference value.

    Works from any directory. Uses PreferencesWorkflow for all operations.
    """
    # Lazy imports
    import json
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    try:
        workflow = PreferencesWorkflow()
        success, message, value = workflow.get_preference(key=args.key)

        if success:
            # Pretty print the value
            if isinstance(value, (dict, list)):
                print(json.dumps(value, indent=2))
            else:
                print(value)
            sys.exit(0)
        else:
            print(f"Error: {message}", file=sys.stderr)
            sys.exit(1)
    except Exception as e:
        print(f"Error: Failed to get preference: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_preferences_set(args):
    """Set a preference value.

    Works from any directory. Uses PreferencesWorkflow for all operations.
    """
    # Lazy imports
    import json
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    # Try to parse value as JSON first, fall back to string
    value = args.value
    try:
        value = json.loads(args.value)
    except json.JSONDecodeError:
        # Keep as string if not valid JSON
        pass

    workflow = PreferencesWorkflow()
    success, message = workflow.set_preference(key=args.key, value=value)
    print(message)
    sys.exit(0 if success else 1)


def cmd_preferences_delete(args):
    """Delete a preference.

    Works from any directory. Uses PreferencesWorkflow for all operations.
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    try:
        workflow = PreferencesWorkflow()
        success, message = workflow.delete_preference(key=args.key)
        print(message)
        sys.exit(0 if success else 1)
    except Exception as e:
        print(f"Error: Failed to delete preference: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_preferences_list(args):
    """List all preferences.

    Works from any directory. Uses PreferencesWorkflow for all operations.
    """
    # Lazy imports
    import json
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    workflow = PreferencesWorkflow()
    success, message, prefs = workflow.list_preferences()

    if prefs:
        print(json.dumps(prefs, indent=2))
    else:
        print(message)
    sys.exit(0)


def cmd_preferences_clear(args):
    """Clear all preferences.

    Works from any directory. Uses PreferencesWorkflow for all operations.
    """
    # Lazy imports
    from myagents.backend.services.agents.workflows.setup_workflow import PreferencesWorkflow

    workflow = PreferencesWorkflow()
    success, message = workflow.clear_preferences()
    print(message)
    sys.exit(0 if success else 1)


def cmd_config_set_path(args):
    """Set config file path preference (delegates to gcptoolkit)."""
    # Lazy import from agent_gcptoolkit
    from agent_gcptoolkit.cli.main import cmd_config_set_path as gcptoolkit_cmd_config_set_path

    # Delegate to gcptoolkit implementation
    gcptoolkit_cmd_config_set_path(args)


def cmd_config_show(args):
    """Show current config file path (delegates to gcptoolkit)."""
    # Lazy import from agent_gcptoolkit
    from agent_gcptoolkit.cli.main import cmd_config_show as gcptoolkit_cmd_config_show

    # Delegate to gcptoolkit implementation
    gcptoolkit_cmd_config_show(args)


def cmd_config_clear(args):
    """Clear config path preference (delegates to gcptoolkit)."""
    # Lazy import from agent_gcptoolkit
    from agent_gcptoolkit.cli.main import cmd_config_clear as gcptoolkit_cmd_config_clear

    # Delegate to gcptoolkit implementation
    gcptoolkit_cmd_config_clear(args)


def cmd_config_init(args):
    """Interactive config setup (delegates to gcptoolkit)."""
    # Lazy import from agent_gcptoolkit
    from agent_gcptoolkit.cli.main import cmd_config_init as gcptoolkit_cmd_config_init

    # Delegate to gcptoolkit implementation
    gcptoolkit_cmd_config_init(args)


def cmd_config_verify(args):
    """Verify config file is valid and complete.

    Checks:
    - Config file exists at ~/.config/agent-gcptoolkit/config.yml or preference location
    - Config file is valid YAML
    - Has required sections: authentication, gcp
    - Has required fields: authentication.type, authentication.service_account_path, gcp.project_id
    - Service account file exists and is readable

    Exit codes:
    - 0: Configuration is valid
    - 1: Configuration is invalid
    """
    # Lazy imports
    from agent_gcptoolkit.secrets.domains.config_loader import _get_config_path
    from myagents.backend.services.agents.domains.config_checker import validate_config

    try:
        # Get config path (uses same logic as config show)
        config_path = _get_config_path()

        # Run validation
        is_valid, errors = validate_config(config_path)

        if is_valid:
            print("✓ Configuration is valid")
            print(f"  Config file: {config_path}")
            sys.exit(0)
        else:
            print("✗ Configuration is invalid")
            print(f"  Config file: {config_path}")
            print()
            print("Errors found:")
            for error in errors:
                print(f"  - {error}")
            sys.exit(1)

    except FileNotFoundError as e:
        # Config file not found at all
        print("✗ Configuration not found")
        print()
        print(str(e))
        sys.exit(1)
    except Exception as e:
        # Unexpected error
        print(f"✗ Error verifying configuration: {e}")
        sys.exit(1)


def cmd_config_list(args):
    """List all current config settings.

    Works from any directory. Shows:
    - Config file location
    - Config routing information
    - Current config settings

    Exit codes:
    - 0: Successfully listed config
    - 1: Error listing config
    """
    # Lazy imports
    import yaml  # type: ignore[import-untyped]
    from pathlib import Path
    from agent_gcptoolkit.secrets.domains.config_loader import _get_config_path
    from myagents.backend.services.agents.workflows.health_check_workflow import HealthCheckWorkflow

    try:
        # Get config path (returns string, convert to Path)
        config_path_str = _get_config_path()
        config_path = Path(config_path_str)

        print("=" * 60)
        print("MyAgents Configuration")
        print("=" * 60)
        print(f"Config file: {config_path}")

        # Check if file exists
        if not config_path.exists():
            print()
            print("Status: Config file does not exist")
            print()
            print("To create a config file, run:")
            print("  myagents config init")
            sys.exit(0)

        # Try to detect routing information
        workflow = HealthCheckWorkflow()
        try:
            detected_config = workflow.detect_config_path()
            if detected_config and detected_config != config_path:
                print(f"Routed from: {detected_config}")
        except Exception:
            # Routing detection failed, that's okay
            pass

        # Load and display config contents
        try:
            with open(config_path, 'r') as f:
                config_data = yaml.safe_load(f)

            if config_data:
                print()
                print("Current settings:")
                print(yaml.dump(config_data, default_flow_style=False, indent=2))
            else:
                print()
                print("Status: Config file is empty")
        except yaml.YAMLError as e:
            print()
            print(f"Warning: Config file contains invalid YAML: {e}")
        except Exception as e:
            print()
            print(f"Warning: Could not read config file: {e}")

        print("=" * 60)
        sys.exit(0)

    except FileNotFoundError as e:
        print("Error: Configuration not found")
        print()
        print(str(e))
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


def cmd_secrets_get(args):
    """Get a secret from GCP Secret Manager (delegates to gcptoolkit)."""
    # Lazy import from agent_gcptoolkit
    from agent_gcptoolkit.cli.main import cmd_secrets_get as gcptoolkit_cmd_secrets_get

    # Delegate to gcptoolkit implementation
    gcptoolkit_cmd_secrets_get(args)


def _get_gcptoolkit_root():
    """Find the Agent-GCPtoolkit repository root.

    Returns:
        Path: Path to Agent-GCPtoolkit directory

    Raises:
        RuntimeError: If Agent-GCPtoolkit cannot be found
    """
    # Try multiple locations
    possible_locations = [
        project_dir.parent / "Agent-GCPtoolkit" if project_dir else None,  # sibling directory (local dev)
        project_dir / "Agent-GCPtoolkit" if project_dir else None,  # inside workspace (Docker)
        Path.home() / "myagents" / "Agent-GCPtoolkit",  # home directory
        Path("/home/code/myagents/Agent-GCPtoolkit"),  # hardcoded fallback
    ]

    for location in possible_locations:
        if location and location.exists() and (location / "pyproject.toml").exists():
            # Verify it's actually agent-gcptoolkit by checking pyproject.toml
            import tomllib
            try:
                with open(location / "pyproject.toml", "rb") as f:
                    data = tomllib.load(f)
                    if data.get("project", {}).get("name") == "agent-gcptoolkit":
                        return location
            except Exception:
                continue

    raise RuntimeError("Agent-GCPtoolkit repository not found")


def cmd_gcptoolkit_build(args):
    """Build agent-gcptoolkit package."""
    import os
    import subprocess
    import shutil

    # Find gcptoolkit root
    try:
        gcptoolkit_root = _get_gcptoolkit_root()
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Build the package using python -m build
    print(f"Building agent-gcptoolkit from {gcptoolkit_root}...")

    # Ensure build-artifacts/dist directory exists
    dist_dir = gcptoolkit_root / "build-artifacts" / "dist"

    # Clean previous build
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    dist_dir.mkdir(parents=True)

    # Build package
    env = os.environ.copy()
    env["PIP_NO_INPUT"] = "1"

    result = subprocess.run(
        ["python", "-m", "build", "--installer", "uv", "--outdir", str(dist_dir)],
        cwd=str(gcptoolkit_root),
        env=env
    )

    if result.returncode == 0:
        print("✓ Build complete")
        print(f"  Artifacts: {dist_dir}")
    else:
        print("✗ Build failed", file=sys.stderr)

    sys.exit(result.returncode)


def cmd_gcptoolkit_update(args):
    """Update agent-gcptoolkit package from latest build."""
    import os
    import subprocess

    # Find gcptoolkit root
    try:
        gcptoolkit_root = _get_gcptoolkit_root()
    except RuntimeError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    # Find the latest wheel
    dist_dir = gcptoolkit_root / "build-artifacts" / "dist"
    if not dist_dir.exists():
        print("Error: No build artifacts found. Run 'myagents gcptoolkit build' first.", file=sys.stderr)
        sys.exit(1)

    wheels = list(dist_dir.glob("agent_gcptoolkit-*.whl"))
    if not wheels:
        print(f"Error: No wheel found in {dist_dir}. Run 'myagents gcptoolkit build' first.", file=sys.stderr)
        sys.exit(1)

    # Use the first wheel (should only be one)
    wheel = wheels[0]
    print(f"Updating agent-gcptoolkit from {wheel.name}...")

    # Install using uv pip (or fall back to regular pip)
    env = os.environ.copy()
    env["PIP_NO_INPUT"] = "1"

    # Use uv pip
    result = subprocess.run(
        ["uv", "pip", "install", "--force-reinstall", str(wheel)],
        env=env,
        capture_output=True
    )

    if result.returncode == 0:
        print("✓ Update complete")
    else:
        print("✗ Update failed", file=sys.stderr)

    sys.exit(result.returncode)


def cmd_gcptoolkit_rebuild(args):
    """Rebuild agent-gcptoolkit package (build + update)."""
    # Run build first
    cmd_gcptoolkit_build(args)

    # If build succeeded (would have exited on failure), run update
    # Note: build exits on failure, so we only reach here if it succeeded
    cmd_gcptoolkit_update(args)


def cmd_update(args):
    """Reinstall myagents from current source.

    Works from any directory.
    """
    source_root = project_dir
    print(f"Updating myagents from source: {source_root}")

    try:
        # Use uv sync to properly resolve and install all dependencies
        result = subprocess.run(
            ["uv", "sync"],
            cwd=str(source_root),
            capture_output=True,
            text=True
        )

        if result.returncode == 0:
            print("Update complete")
            print("Successfully updated myagents")
            if result.stdout:
                print(result.stdout)
            sys.exit(0)
        else:
            print("Error updating myagents:", file=sys.stderr)
            if result.stderr:
                print(result.stderr, file=sys.stderr)
            sys.exit(1)

    except FileNotFoundError as e:
        print(f"Error: Installation tool not found: {e}", file=sys.stderr)
        print("Please ensure pip or uv is available in your PATH", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_rebuild(args):
    """Rebuild and reinstall myagents package.

    Works from any directory.
    """
    source_root = project_dir
    print(f"Rebuilding myagents package from source: {source_root}")

    try:
        # Clean previous build artifacts
        build_dir = source_root / "build"
        dist_dir = source_root / "dist"
        egg_dir = source_root / "myagents.egg-info"

        print("Cleaning previous build artifacts...")
        for dir_path in [build_dir, dist_dir, egg_dir]:
            if dir_path.exists():
                subprocess.run(
                    ["rm", "-rf", str(dir_path)],
                    check=True,
                    capture_output=True
                )

        # Build the package
        print("Building package...")
        env = os.environ.copy()
        env["PIP_NO_INPUT"] = "1"  # Prevent pip from prompting for credentials
        build_result = subprocess.run(
            ["python", "-m", "build", "--installer", "uv"],
            cwd=str(source_root),
            capture_output=True,
            text=True,
            env=env
        )

        if build_result.returncode != 0:
            print("Error building package:", file=sys.stderr)
            if build_result.stderr:
                print(build_result.stderr, file=sys.stderr)
            sys.exit(1)

        # Reinstall the package
        print("Reinstalling package...")
        install_result = subprocess.run(
            ["uv", "sync"],
            cwd=str(source_root),
            capture_output=True,
            text=True,
            env=env
        )

        if install_result.returncode == 0:
            print("Build complete")
            print("Successfully rebuilt and reinstalled myagents")
            if install_result.stdout:
                print(install_result.stdout)
            sys.exit(0)
        else:
            print("Error reinstalling myagents:", file=sys.stderr)
            if install_result.stderr:
                print(install_result.stderr, file=sys.stderr)
            sys.exit(1)

    except FileNotFoundError as e:
        print(f"Error: Required tool not found: {e}", file=sys.stderr)
        print("Please ensure python build tools are available", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


def cmd_setup(args):
    """Run initial setup workflow.

    Creates configuration in home directory (~/.config/myagents/config.yml)
    if it doesn't already exist. This should be run once after installation.

    Args:
        args: Parsed command-line arguments (if any flags added)

    Returns:
        int: Exit code (0 for success, 1 for failure)
    """
    try:
        # Import setup workflow
        from myagents.backend.services.agents.workflows.setup_workflow import SetupWorkflow

        # Create workflow instance
        workflow = SetupWorkflow()

        # Run setup
        success, message = workflow.run_setup()

        # Display result (FIX-003: Enhanced error handling with logging)
        if success:
            print(f"✓ {message}")
            return 0
        else:
            import logging
            logging.error(f"Setup failed: {message}")
            logging.error("This may indicate a package installation issue")
            print(f"✗ {message}", file=sys.stderr)
            sys.exit(1)

    except Exception as e:
        print(f"Error: Setup failed: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        return 1


def main():
    """Main CLI entry point."""
    # Block direct execution
    if project_dir is None:
        print("Error: myagents_cli.py should not be run directly. Use 'myagents' command instead.", file=sys.stderr)
        sys.exit(1)

    parser = argparse.ArgumentParser(
        description="MyAgents - LangGraph agent framework with Studio integration",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        add_help=True,
        epilog="""
Examples:
  # List available agents
  myagents agents

  # Start interactive agent chat
  myagents chat
  myagents chat --agent builder

  # Run cleaner agent (two-phase cleanup)
  myagents clean --identify path/to/plan.yml
  myagents clean --execute path/to/plan.yml

  # Run test agent
  myagents test --run
  myagents test --audit
  myagents test --simulate

  # Run explore agent
  myagents explore --arch
  myagents explore --feature
  myagents explore --dep
  myagents explore --test
  myagents explore --synth

  # Start LangGraph Studio
  myagents studio start
  myagents studio start --port 3000

  # Check Studio status
  myagents studio status

  # Stop Studio
  myagents studio stop
  myagents studio stop --force

  # Restart Studio
  myagents studio restart

  # Start Relay Service
  myagents relay start
  myagents relay start --port 9000
  myagents relay start --host localhost --port 8080

  # Check Relay status
  myagents relay status

  # Stop Relay
  myagents relay stop
  myagents relay stop --force

  # Start Remote Terminal Service
  myagents remote start
  myagents remote start --port 8080
  myagents remote start --relay-url ws://relay.example.com:8080

  # Check Remote Terminal status
  myagents remote status

  # Stop Remote Terminal
  myagents remote stop
  myagents remote stop --force

  # Common workflows
  # Start relay and remote services together
  myagents relay start --host 0.0.0.0 --port 8080
  myagents remote start --port 8080 --relay-url ws://localhost:8080

  # Check status of all services
  myagents studio status
  myagents relay status
  myagents remote status

  # Manage preferences
  myagents preferences set agent.default coding
  myagents preferences get agent.default
  myagents preferences set studio.port 3000
  myagents preferences list
  myagents preferences delete agent.default

  # Manage configuration
  myagents config init
  myagents config set-path /path/to/config.yml
  myagents config show
  myagents config clear
  myagents config verify

  # Manage secrets
  myagents secrets get GEMINI_API_KEY
  myagents secrets get MY_SECRET --project-id my-project
  myagents secrets get MY_SECRET -q

  # Update and rebuild
  myagents update
  myagents rebuild
"""
    )

    # Add --version argument
    parser.add_argument(
        "--version", "-v",
        action="version",
        version=get_version()
    )

    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Chat command
    parser_chat = subparsers.add_parser(
        "chat",
        help="Start interactive agent chat",
        aliases=["c"]
    )
    parser_chat.add_argument(
        "--agent", "-a",
        default="builder",
        metavar="AGENT",
        help="Agent type to use (default: builder). Use 'myagents agents' to list available agents."
    )
    parser_chat.set_defaults(func=cmd_agent_chat)

    # Agents command - list available agents
    parser_agents = subparsers.add_parser(
        "agents",
        help="List all available agents",
        description="Show all registered agents grouped by category with descriptions."
    )
    parser_agents.set_defaults(func=cmd_agents_list)

    # Clean command - cleaner agents
    parser_clean = subparsers.add_parser(
        "clean",
        help="Run cleaner agent (two-phase cleanup)",
        description="Run cleaner agent for codebase cleanup. Two-phase process: "
                    "identify targets first, then execute approved changes."
    )
    clean_mode = parser_clean.add_mutually_exclusive_group(required=True)
    clean_mode.add_argument(
        "--identify", "-i",
        action="store_true",
        help="Identification mode - scan for cleanup targets (no changes)"
    )
    clean_mode.add_argument(
        "--execute", "-e",
        action="store_true",
        help="Execution mode - process approved cleanup targets"
    )
    parser_clean.add_argument(
        "plan_path",
        help="Path to the live plan file for context"
    )
    parser_clean.set_defaults(func=cmd_clean)

    # Test command - test agents
    parser_test = subparsers.add_parser(
        "test",
        help="Run test agent",
        description="Run test agent for test execution, auditing, or user simulation."
    )
    test_mode = parser_test.add_mutually_exclusive_group(required=True)
    test_mode.add_argument(
        "--run", "-r",
        action="store_true",
        help="Run tests and report results"
    )
    test_mode.add_argument(
        "--audit", "-a",
        action="store_true",
        help="Review test quality and skip patterns"
    )
    test_mode.add_argument(
        "--simulate", "-s",
        action="store_true",
        help="Test from user/documentation perspective"
    )
    parser_test.add_argument(
        "target",
        nargs="?",
        default=None,
        help="Optional target path or test specification"
    )
    parser_test.set_defaults(func=cmd_test)

    # Explore command - explore agents
    parser_explore = subparsers.add_parser(
        "explore",
        help="Run explore agent for codebase analysis",
        description="Run explore agent to analyze codebase architecture, features, "
                    "dependencies, tests, or synthesize findings."
    )
    explore_mode = parser_explore.add_mutually_exclusive_group(required=True)
    explore_mode.add_argument(
        "--arch",
        action="store_true",
        help="Analyze project architecture"
    )
    explore_mode.add_argument(
        "--feature",
        action="store_true",
        help="Analyze feature implementations"
    )
    explore_mode.add_argument(
        "--dep",
        action="store_true",
        help="Map project dependencies"
    )
    explore_mode.add_argument(
        "--test",
        action="store_true",
        help="Analyze testing patterns"
    )
    explore_mode.add_argument(
        "--synth",
        action="store_true",
        help="Combine all exploration findings"
    )
    parser_explore.add_argument(
        "target",
        nargs="?",
        default=None,
        help="Optional target path or exploration focus"
    )
    parser_explore.set_defaults(func=cmd_explore)

    # Studio command
    parser_studio = subparsers.add_parser(
        "studio",
        help="Manage LangGraph Studio"
    )
    studio_subparsers = parser_studio.add_subparsers(
        dest="studio_command",
        help="Studio command"
    )

    # Studio start
    parser_start = studio_subparsers.add_parser(
        "start",
        help="Start LangGraph Studio"
    )
    parser_start.add_argument(
        "--port", "-p",
        type=int,
        default=None,
        help="Port for Studio server (default: uses preference or config)"
    )
    parser_start.add_argument(
        "--foreground", "-f",
        action="store_true",
        help="Run in foreground instead of background"
    )
    parser_start.set_defaults(func=cmd_studio_start)

    # Studio stop
    parser_stop = studio_subparsers.add_parser(
        "stop",
        help="Stop LangGraph Studio"
    )
    parser_stop.add_argument(
        "--force",
        action="store_true",
        help="Force kill if graceful shutdown fails"
    )
    parser_stop.set_defaults(func=cmd_studio_stop)

    # Studio restart
    parser_restart = studio_subparsers.add_parser(
        "restart",
        help="Restart LangGraph Studio"
    )
    parser_restart.set_defaults(func=cmd_studio_restart)

    # Studio status
    parser_status = studio_subparsers.add_parser(
        "status",
        help="Show LangGraph Studio status"
    )
    parser_status.set_defaults(func=cmd_studio_status)

    # Relay command
    parser_relay = subparsers.add_parser(
        "relay",
        help="Manage Relay Service",
        description="Manage the WebSocket relay server that connects desktop clients with remote terminals"
    )
    relay_subparsers = parser_relay.add_subparsers(
        dest="relay_command",
        help="Relay command"
    )

    # Relay start
    parser_relay_start = relay_subparsers.add_parser(
        "start",
        help="Start Relay Service"
    )
    parser_relay_start.add_argument(
        "--port", "-p",
        type=int,
        default=8080,
        help="Port for relay server (default: 8080)"
    )
    parser_relay_start.add_argument(
        "--host",
        type=str,
        default="0.0.0.0",
        help="Host for relay server (default: 0.0.0.0)"
    )
    parser_relay_start.add_argument(
        "--foreground", "-f",
        action="store_true",
        help="Run in foreground instead of background"
    )
    parser_relay_start.set_defaults(func=cmd_relay_start)

    # Relay stop
    parser_relay_stop = relay_subparsers.add_parser(
        "stop",
        help="Stop Relay Service"
    )
    parser_relay_stop.add_argument(
        "--force",
        action="store_true",
        help="Force kill if graceful shutdown fails"
    )
    parser_relay_stop.set_defaults(func=cmd_relay_stop)

    # Relay status
    parser_relay_status = relay_subparsers.add_parser(
        "status",
        help="Show Relay Service status"
    )
    parser_relay_status.set_defaults(func=cmd_relay_status)

    # Remote command
    parser_remote = subparsers.add_parser(
        "remote",
        help="Manage Remote Terminal Service",
        description="Manage the remote terminal service that provides WebSocket-based terminal access"
    )
    remote_subparsers = parser_remote.add_subparsers(
        dest="remote_command",
        help="Remote Terminal command"
    )

    # Remote start
    parser_remote_start = remote_subparsers.add_parser(
        "start",
        help="Start Remote Terminal Service"
    )
    parser_remote_start.add_argument(
        "--port", "-p",
        type=int,
        default=8080,
        help="Port for terminal service (default: 8080)"
    )
    parser_remote_start.add_argument(
        "--relay-url",
        type=str,
        help="WebSocket relay URL (default: ws://localhost:8080)"
    )
    parser_remote_start.add_argument(
        "--foreground", "-f",
        action="store_true",
        help="Run in foreground instead of background"
    )
    parser_remote_start.set_defaults(func=cmd_remote_start)

    # Remote stop
    parser_remote_stop = remote_subparsers.add_parser(
        "stop",
        help="Stop Remote Terminal Service"
    )
    parser_remote_stop.add_argument(
        "--force",
        action="store_true",
        help="Force kill if graceful shutdown fails"
    )
    parser_remote_stop.set_defaults(func=cmd_remote_stop)

    # Remote status
    parser_remote_status = remote_subparsers.add_parser(
        "status",
        help="Show Remote Terminal Service status"
    )
    parser_remote_status.set_defaults(func=cmd_remote_status)

    # Preferences command
    parser_prefs = subparsers.add_parser(
        "preferences",
        help="Manage user preferences",
        aliases=["prefs", "pref"]
    )
    prefs_subparsers = parser_prefs.add_subparsers(
        dest="preferences_command",
        help="Preferences command"
    )

    # Preferences get
    parser_prefs_get = prefs_subparsers.add_parser(
        "get",
        help="Get a preference value"
    )
    parser_prefs_get.add_argument(
        "key",
        help="Preference key (supports dot notation like 'agent.default')"
    )
    parser_prefs_get.set_defaults(func=cmd_preferences_get)

    # Preferences set
    parser_prefs_set = prefs_subparsers.add_parser(
        "set",
        help="Set a preference value"
    )
    parser_prefs_set.add_argument(
        "key",
        help="Preference key (supports dot notation like 'agent.default')"
    )
    parser_prefs_set.add_argument(
        "value",
        help="Preference value (JSON or string)"
    )
    parser_prefs_set.set_defaults(func=cmd_preferences_set)

    # Preferences delete
    parser_prefs_delete = prefs_subparsers.add_parser(
        "delete",
        help="Delete a preference",
        aliases=["del", "rm"]
    )
    parser_prefs_delete.add_argument(
        "key",
        help="Preference key to delete"
    )
    parser_prefs_delete.set_defaults(func=cmd_preferences_delete)

    # Preferences list
    parser_prefs_list = prefs_subparsers.add_parser(
        "list",
        help="List all preferences",
        aliases=["ls"]
    )
    parser_prefs_list.set_defaults(func=cmd_preferences_list)

    # Preferences clear
    parser_prefs_clear = prefs_subparsers.add_parser(
        "clear",
        help="Clear all preferences"
    )
    parser_prefs_clear.set_defaults(func=cmd_preferences_clear)

    # Config command
    parser_config = subparsers.add_parser(
        "config",
        help="Configuration management"
    )
    config_subparsers = parser_config.add_subparsers(
        dest="config_command",
        help="Config command"
    )

    # Config set-path
    parser_config_set_path = config_subparsers.add_parser(
        "set-path",
        help="Set config file path"
    )
    parser_config_set_path.add_argument(
        "path",
        help="Path to config file"
    )
    parser_config_set_path.set_defaults(func=cmd_config_set_path)

    # Config show
    parser_config_show = config_subparsers.add_parser(
        "show",
        help="Show current config path"
    )
    parser_config_show.set_defaults(func=cmd_config_show)

    # Config clear
    parser_config_clear = config_subparsers.add_parser(
        "clear",
        help="Clear config path preference"
    )
    parser_config_clear.set_defaults(func=cmd_config_clear)

    # Config init
    parser_config_init = config_subparsers.add_parser(
        "init",
        help="Interactive config setup"
    )
    parser_config_init.set_defaults(func=cmd_config_init)

    # Config verify
    parser_config_verify = config_subparsers.add_parser(
        "verify",
        help="Verify config file is valid"
    )
    parser_config_verify.set_defaults(func=cmd_config_verify)

    # Config list
    parser_config_list = config_subparsers.add_parser(
        "list",
        help="List all current config settings"
    )
    parser_config_list.set_defaults(func=cmd_config_list)

    # Secrets command
    parser_secrets = subparsers.add_parser(
        "secrets",
        help="Secret management operations"
    )
    secrets_subparsers = parser_secrets.add_subparsers(
        dest="secrets_command",
        help="Secrets command"
    )

    # Secrets get
    parser_secrets_get = secrets_subparsers.add_parser(
        "get",
        help="Get a secret value",
        description="""
Fetch a secret from GCP Secret Manager with automatic fallback to environment variables.

Behavior:
  1. Checks memory cache (within same process only)
  2. Fetches from GCP Secret Manager
  3. Falls back to environment variable if GCP fetch fails

The command will print the secret value to stdout. In quiet mode (-q),
only the value is printed. In normal mode, the secret name is also shown.

Exit codes:
  0 - Secret found and printed
  1 - Secret not found (not in GCP or environment)
  2 - Invalid secret name format
        """
    )
    parser_secrets_get.add_argument(
        "secret_name",
        help="Name of the secret (format: [a-zA-Z0-9_-]+, no dots or special chars)"
    )
    parser_secrets_get.add_argument(
        "--project-id",
        help="GCP project ID (auto-detected from GCP_PROJECT env var or config file if not provided)"
    )
    parser_secrets_get.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Output only the secret value (suppresses warnings and formatting, useful for scripts)"
    )
    parser_secrets_get.set_defaults(func=cmd_secrets_get)

    # GCPToolkit command (for building/managing agent-gcptoolkit itself)
    parser_gcptoolkit = subparsers.add_parser(
        "gcptoolkit",
        help="Manage agent-gcptoolkit package"
    )
    gcptoolkit_subparsers = parser_gcptoolkit.add_subparsers(
        dest="gcptoolkit_command",
        help="GCPToolkit command"
    )

    # GCPToolkit build
    parser_gcptoolkit_build = gcptoolkit_subparsers.add_parser(
        "build",
        help="Build agent-gcptoolkit package"
    )
    parser_gcptoolkit_build.set_defaults(func=cmd_gcptoolkit_build)

    # GCPToolkit update
    parser_gcptoolkit_update = gcptoolkit_subparsers.add_parser(
        "update",
        help="Update agent-gcptoolkit package"
    )
    parser_gcptoolkit_update.set_defaults(func=cmd_gcptoolkit_update)

    # GCPToolkit rebuild
    parser_gcptoolkit_rebuild = gcptoolkit_subparsers.add_parser(
        "rebuild",
        help="Rebuild agent-gcptoolkit package"
    )
    parser_gcptoolkit_rebuild.set_defaults(func=cmd_gcptoolkit_rebuild)

    # Update command
    parser_update = subparsers.add_parser(
        "update",
        help="Reinstall myagents from current source"
    )
    parser_update.set_defaults(func=cmd_update)

    # Rebuild command
    parser_rebuild = subparsers.add_parser(
        "rebuild",
        help="Rebuild and reinstall myagents package"
    )
    parser_rebuild.set_defaults(func=cmd_rebuild)

    # Setup command
    parser_setup = subparsers.add_parser(
        "setup",
        help="Run initial setup workflow",
        description="Initialize MyAgents configuration in home directory. "
                    "Creates ~/.config/myagents/config.yml with default settings."
    )
    parser_setup.set_defaults(func=cmd_setup)

    # Parse arguments
    args = parser.parse_args()

    # Show help if no command specified (better UX - works from anywhere)
    if not args.command:
        parser.print_help()
        sys.exit(0)

    # Execute command
    if hasattr(args, "func"):
        args.func(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
